#!/bin/sh

git rev-parse --git-dir >/dev/null 2>&1 || {
  printf 'git rs: not inside a Git repository\n' >&2
  exit 1
}

git reflog show --pretty=format:'%gs ~ %gd' --date=relative |
  grep 'checkout:' |
  grep -oE '[^ ]* ~ .*' |
  awk -F~ '!seen[$1]++' |
  awk -F' ~ HEAD@{' '{printf(" \033[33m%s: \033[37m %s\033[0m\n", substr($2, 1, length($2)-1), $1)}'
